language: ruby
rvm: 2.5.3
services:
  - postgresql
env:
  global:
    - PGHOST=localhost
    - PGUSER=postgres
before_install:
  - gem update --system
  - gem install bundler
  - bundle install
  - rake db:create
  - rake db:migrate:test
