source "http://rubygems.org"

gem "activerecord", "~> 6.1"
gem "haml", "~> 5.2"
gem "mongoid", "~> 7.3"
gem "pg", "~> 1.2"
gem "psych", "~> 4.0"
gem "puma", "~> 5.5"
gem "rake", "~> 13.0"
gem "sinatra", "~> 2.1"
gem "sinatra-activerecord", "~> 2.0"
gem "webpush", "~> 1.1"
