default:
  adapter:  postgresql
  encoding: utf-8
  host:     localhost
  port:     5432
  database: poistatkai
  username: postgres
  password: 123
  pool:     10

development:
  adapter:  postgresql
  encoding: utf-8
  host:     localhost
  port:     5432
  database: poistatkai
  username: postgres
  password: 123
  pool:     10

production:
  adapter:  postgresql
  encoding: utf-8
  host:     localhost
  port:     5432
  database: poistatkai
  username: postgres
  password: 123
  pool:     10