default:
  clients:
    default:
      database: poi-production
      hosts:
        - localhost:27017

development:
  clients:
    default:
      database: poi-production
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: poi-production
      hosts:
        - localhost:27017
