name: Ruby
on:
  push:
    branches:
    - master
    - dev
    - feat-*
  pull_request:
    branches:
    - master
    - dev
env:
  PGHOST: localhost
  PGUSER: postgres
  PGPASSWORD: postgres
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: '11'
        postgresql user: postgres
        postgresql password: postgres
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Install dependencies
      run: bundle install
    - name: Set up database
      run: |
        bundle exec rake db:create
        bundle exec rake db:migrate
    - name: Run tests
      run: bundle exec rake
